# Generated by Django 5.2.5 on 2025-08-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('PERDIDO', 'Perdido'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='etapas',
            field=models.ManyToManyField(blank=True, null=True, related_name='pipelines', to='kanban.etapa'),
        ),
    ]
