# Generated by Django 5.2.5 on 2025-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_categoria_card_propriedade_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='etapas',
            field=models.ManyToManyField(blank=True, related_name='pipelines', to='kanban.etapa'),
        ),
    ]
