# Generated by Django 5.2.5 on 2025-08-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_tarefa_atribuido_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.pipeline'),
        ),
    ]
