# Generated by Django 5.2.5 on 2025-08-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_card_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='tipo',
            field=models.CharField(blank=True, choices=[('text', 'Texto'), ('number', 'Número'), ('bool', 'Booleano'), ('date', 'Data'), ('select', 'Seleção')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PipelinePropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('bool', 'Booleano'), ('date', 'Data'), ('select', 'Seleção')], max_length=100)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('opcoes', models.JSONField(blank=True, null=True)),
                ('valor_padrao', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades_def', to='kanban.categoria')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades_def', to='kanban.pipeline')),
            ],
            options={
                'ordering': ['ordem', 'id'],
                'unique_together': {('pipeline', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='propriedade',
            name='definicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='kanban.pipelinepropriedade'),
        ),
    ]
