# Generated by Django 5.2.5 on 2025-08-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_remove_propriedade_categoria_alter_propriedade_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinepropriedade',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
