# Generated by Django 5.2.5 on 2025-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_checklist_checklistitem_tarefa_checklist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='depende_de',
            field=models.ManyToManyField(blank=True, related_name='dependentes', to='kanban.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='requer_aprovacao',
            field=models.BooleanField(default=False),
        ),
    ]
