# Generated by Django 5.2.5 on 2025-09-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0010_checklistitem_depende_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='etapa',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='vinculado_a_etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='kanban.etapa'),
        ),
    ]
