# Generated by Django 5.2.5 on 2025-09-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador_erp', '0003_alter_contratolocacao_taxa_administracao_and_more'),
        ('kanban', '0012_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cliente_associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importador_erp.cliente'),
        ),
        migrations.AddField(
            model_name='card',
            name='contrato_locacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importador_erp.contratolocacao'),
        ),
    ]
