# Generated by Django 5.2.5 on 2025-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador_erp', '0003_alter_contratolocacao_taxa_administracao_and_more'),
        ('kanban', '0013_card_cliente_associado_card_contrato_locacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cliente_associado',
        ),
        migrations.RemoveField(
            model_name='card',
            name='contrato_locacao',
        ),
        migrations.AddField(
            model_name='card',
            name='clientes_associado',
            field=models.ManyToManyField(blank=True, null=True, to='importador_erp.cliente'),
        ),
        migrations.AddField(
            model_name='card',
            name='contratos_locacao',
            field=models.ManyToManyField(blank=True, null=True, to='importador_erp.contratolocacao'),
        ),
    ]
