# Generated by Django 5.2.5 on 2025-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador_erp', '0003_alter_contratolocacao_taxa_administracao_and_more'),
        ('kanban', '0014_remove_card_cliente_associado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='clientes_associado',
            field=models.ManyToManyField(blank=True, to='importador_erp.cliente'),
        ),
        migrations.AlterField(
            model_name='card',
            name='contratos_locacao',
            field=models.ManyToManyField(blank=True, to='importador_erp.contratolocacao'),
        ),
    ]
