# Generated by Django 5.2.5 on 2025-09-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0016_alter_card_clientes_associado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='clientes_associado',
            new_name='clientes_associados',
        ),
    ]
