# Generated by Django 5.2.5 on 2025-09-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_clientelicense_apelido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_pessoa', models.IntegerField(unique=True)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('PROPRIETARIO', 'Proprietário'), ('INQUILINO', 'Inquilino'), ('FIADOR', 'Fiador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_contrato', models.IntegerField(unique=True)),
                ('nome_do_imovel', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('aluguel_garantido', models.BooleanField(default=False)),
                ('tipo_garantia', models.CharField(max_length=100)),
                ('data_inicio_garantia', models.DateField(blank=True, null=True)),
                ('data_fim_garantia', models.DateField(blank=True, null=True)),
                ('data_inicio_seguro_incendio', models.DateField(blank=True, null=True)),
                ('data_fim_seguro_incendio', models.DateField(blank=True, null=True)),
                ('data_ultimo_reajuste', models.DateField(blank=True, null=True)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_administracao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxa_locacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_venda_imovel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_garantia_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_seguro_incendio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_imovel', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('status_contrato', models.CharField(max_length=100)),
                ('contrato_ativo', models.BooleanField(default=True)),
                ('renovacao_automatica', models.BooleanField(default=False)),
                ('inquilinos', models.ManyToManyField(related_name='contratos_inquilino', to='importador_erp.cliente')),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.clientelicense')),
                ('proprietarios', models.ManyToManyField(related_name='contratos_proprietario', to='importador_erp.cliente')),
            ],
        ),
    ]
