# Generated by Django 5.2.5 on 2025-09-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador_erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')], max_length=1),
        ),
    ]
