# Generated by Django 5.2.5 on 2025-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador_erp', '0002_alter_cliente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratolocacao',
            name='taxa_administracao',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='contratolocacao',
            name='taxa_locacao',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
