# Generated by Django 5.2.5 on 2025-08-29 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.SlugField(unique=True)),
                ('apelido', models.CharField(blank=True, help_text='apelido opcional para exibir na UI', max_length=120)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='clientes.pessoa')),
            ],
            options={
                'verbose_name': 'Licença do Cliente',
                'verbose_name_plural': 'Licenças do Cliente',
            },
        ),
    ]
