# Generated by Django 5.2.5 on 2025-08-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientelicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientelicense',
            name='apelido',
            field=models.CharField(blank=True, help_text='apelido opcional para exibir na UI', max_length=120, null=True),
        ),
    ]
