# Generated by Django 5.2.5 on 2025-09-22 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientelicense_apelido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('perfil', 'Perfil'), ('empresa', 'Empresa'), ('integracao', 'Integração'), ('processo', 'Primeiro Processo'), ('resumo', 'Resumo')], default='perfil', max_length=20)),
                ('onboarding_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
