# Generated by Django 5.2.5 on 2025-08-29 19:10

import integrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(help_text='subdomínio da licença, ex: minhaimobiliaria', max_length=120, unique=True)),
                ('access_token', integrador.models.EncryptedTextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Integração de Licença',
                'verbose_name_plural': 'Integrações de Licenças',
            },
        ),
    ]
