# Generated by Django 5.2.5 on 2025-08-29 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientelicense'),
        ('integrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseintegration',
            name='license_name',
        ),
        migrations.AddField(
            model_name='licenseintegration',
            name='license',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integracao', to='clientes.clientelicense'),
        ),
    ]
